// Test Actor
class FancyWallTestSound : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallTestSound", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/test", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Plutonia Waterfalls
class FancyWallWaterfall : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallWaterfall", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/waterfall", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Bloodfalls
class FancyWallBloodfall : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallBloodfall", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/bloodfall", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Doom 2 Slimefalls
class FancyWallSlimefall : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallSlimefall", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/slimefall", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// ObAddon (and prob. others) Lavafalls
class FancyWallLavafall : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallLavafall", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/lavafall", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Doom 1 slime dripping out of a drain
class FancyWallSlimedrip : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallSlimedrip", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/slimedrip", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Gargoyle-head blood fountain
class FancyWallGargfont : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallGargfont", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/slimedrip", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// COMPSTA Wall Computers
class FancyWallCompstation : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallCompstation", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/compstation", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Flaming Walls
class FancyWallFirewall : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFirewall", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/firewall", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// The Battler-Prince
class FancyWallFireblu : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFireblu", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/fireblu", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Creepy Faces on the Wall
class FancyWallFaces : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFaces", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/faces", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Tech Humming
class FancyWallTechhum : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallTechhum", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/techhum", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Lights on the Wall
class FancyWallLights : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallLights", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/walllight", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Static Monitor
class FancyWallStatic : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallStatic", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/static", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}

// Fan
class FancyWallFan : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFan", 16, CPXF_NOZ))
				{
					Destroy();
				}
			}
			TNT1 A 0 A_StartSound("world/fan", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(), ATTN_NORM, frandom(0.98,1.02), frandom(0.0, 1.0));
			APLS A -1;
			loop;
	}
}