// The Great Outdoors
class FancySectorSky : FancyWorldBase
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Idle:
			TNT1 A 0 A_PlaySound("world/fsky", CHAN_BODY, volumecvar.GetFloat(), 1);
			APLS A 72;
			goto Spawn;
		Waiter:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 72;
			goto Spawn;
	}
}

class FancySectorCeilingLite : FancyWorldBase
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Idle:
			TNT1 A 0 A_PlaySound("world/ceilite", CHAN_BODY, volumecvar.GetFloat(), 1);
			APLS A 72;
			goto Spawn;
		Waiter:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 72;
			goto Spawn;
	}
}