// Acid/Nukage
class FancySectorNukageCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Noisy:
			TNT1 A 0 A_PlaySound("world/acidloop", CHAN_BODY, volumecvar.GetFloat(), 1);
			TNT1 A 72;
			goto Spawn;
		
	}
}

class FancySectorNukage : FancyWorldBase
{
	Default
	{
		RenderStyle "Normal";
		+VULNERABLE
	}

	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 8;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
			TNT1 A 0 A_Jump(64, "Idle");
		Waiter:
			TNT1 A 72;
			goto Idle;
		Idle:
			TNT1 A 16 A_Jump(8, "Waiter");
			TNT1 A 0 A_Jump(128,"Croak");
			loop;
		Croak:
			NUBA A 0
			{
				if (floorpic != TexMan.CheckForTexture("NUKAGE1", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("NUKAGE2", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("NUKAGE3", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("NUKAGE4", TexMan.Type_Any))
				{
					Destroy();
				}
			}
			NUBL A 0 A_PlaySound("world/acid", CHAN_VOICE);
			NUBL ABCDE 4;
			goto Spawn;
	}
}

// Water
class FancySectorWaterCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Noisy:
			TNT1 A 0 A_PlaySound("world/waterflow", CHAN_BODY, volumecvar.GetFloat(), 1);
			TNT1 A 72;
			goto Spawn;
		
	}
}

// Slime
class FancySectorSlimeCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Noisy:
			TNT1 A 0 A_PlaySound("world/gooflow", CHAN_AUTO, volumecvar.GetFloat(), 1);
			TNT1 A 72;
			goto Spawn;
		
	}
}

// Lava
class FancySectorLavaCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Noisy:
			TNT1 A 0 A_PlaySound("world/lavaflow", CHAN_AUTO, volumecvar.GetFloat(), 1);
			TNT1 A 72;
			goto Spawn;
		
	}
}

class FancySectorLava : FancyWorldBase
{
	Default
	{
		RenderStyle "Normal";
	}

	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
			TNT1 A 8;
			TNT1 A 0 A_Jump(64, "Idle");
		Waiter:
			TNT1 A 72;
			goto Idle;
		Idle:
			TNT1 A 16 A_Jump(8, "Waiter");
			TNT1 A 0 A_Jump(16,"Parp");
			TNT1 A 0 A_Jump(128,"Croak");
			loop;
		Parp:
			TNT1 A 0 A_SpawnItem("LavaSmoke");
			goto Croak;
		Croak:
			NUBL A 0
			{
				if (floorpic != TexMan.CheckForTexture("LAVA1", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("LAVA2", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("LAVA3", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("LAVA4", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("QLAVA1", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("QLAVA2", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("QLAVA3", TexMan.Type_Any)
				&& floorpic != TexMan.CheckForTexture("QLAVA4", TexMan.Type_Any))
				{
					Destroy();
				}
			}
			NUBL A 0 A_PlaySound("world/lava");
			LABL ABCDE 4;
			goto Spawn;
	}
}

// Hot Surfaces
class FancySectorHotCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
			TNT1 A 8;
			TNT1 A 0 A_Jump(64, "Idle");
		Waiter:
			TNT1 A 72;
			goto Spawn;
		Idle:
			TNT1 A 16 A_Jump(8, "Waiter");
			TNT1 A 0 A_Jump(16,"Parp");
			loop;
		Parp:
			TNT1 A 0 A_SpawnItem("LavaSmoke");
			TNT1 A 0 A_Jump(16,"Hiss");
			goto Spawn;
		Hiss:
			TNT1 A 0 A_PlaySound("world/hotsurface");
			goto Spawn;
	}
}

// XWater from ObAddon
class FancySectorXWaterCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Noisy:
			TNT1 A 0 A_PlaySound("world/xwater", CHAN_AUTO, volumecvar.GetFloat(), 1);
			TNT1 A 72;
			goto Spawn;
		
	}
}

// Floor Teleporter
class FancySectorTeleporterCore : FancyWorldBase
{
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Noisy:
			TNT1 A 0 A_PlaySound("world/floortele", CHAN_BODY, volumecvar.GetFloat(), 1);
			TNT1 A 72;
			goto Spawn;
		
	}
}