class FancyWorldBase : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	
	transient cvar volumecvar;

	states
	{
		Waiter:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 72;
			TNT1 A 0 A_Jump(256, "Spawn");
			goto Spawn;
	}

	override void Tick() {
		if(!volumecvar) {
			volumecvar = cvar.getcvar("fw_volumefactor", players[consoleplayer]);
		}
		super.Tick();
	}
}