// The Great Outdoors
class FancySectorSky : FancyWorldBase
{

	states
	{
		Spawn:
			TNT1 A 0;
			//TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Idle:
			TNT1 A 0 A_StartSound("world/fsky", CHAN_BODY, CHANF_LOOPING|CHANF_LISTENERZ,volumecvar.GetFloat(),	0.25);
			APLS A 72;
			goto Spawn;
		
	}
}

class FancySectorCeilingLite : FancyWorldBase
{

	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_CheckRange(2048,"Waiter",1);
		Idle:
			TNT1 A 0 A_PlaySound("world/ceilite", CHAN_BODY, volumecvar.GetFloat(), 1);
			APLS A 72;
			goto Spawn;
		
	}
}